sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libboost-system-dev libboost-thread-dev
script:
  - mkdir build
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-Werror ..
  - make
after_script:
  - sudo make install
  - pkg-config --modversion console_bridge
